id: I74772DFF
initial_creation_type: ebook
source_metadata:
  id: RDI-KK-21
  title: དཔལ་འཁོར་ལོ་བདེ་མཆོག་ལྷ་ལྔའི་དཀྱིལ་ཆོག་གི་མཆོད་གཞི་བཅའ་བསྒྲིགས་འདོན་ཟིན་ཕྱག་ལེན་རྣམས་ཞིབ་བཀོད།
    གདངས་དབྱངས་འཐེན་གྲངས་བཅས་ཁ་གསལ་གོ་བདེ་ཕྱོགས་གཅིག་ཏུ་བཀོད་པ།
  author: ''
  authors: &id001 []
  sku: RDI-KK-21
  cover: 1.png
  volume: {}
ebook_metadata:
  title: དཔལ་འཁོར་ལོ་བདེ་མཆོག་ལྷ་ལྔའི་དཀྱིལ་ཆོག་གི་མཆོད་གཞི་བཅའ་བསྒྲིགས་འདོན་ཟིན་ཕྱག་ལེན་རྣམས་ཞིབ་བཀོད།
    གདངས་དབྱངས་འཐེན་གྲངས་བཅས་ཁ་གསལ་གོ་བདེ་ཕྱོགས་གཅིག་ཏུ་བཀོད་པ།
  authors: *id001
  sku: RDI-KK-21
  cover: 1.png
layers:
- BookTitle
- Chapter
- Citation
- Commentary
- Sabche
- Tsawa
- Yigchung
